services:
  ros_noetic:
    tty: true
    build: .
    privileged: true
    image: autoware_wheelchair:cpu
    entrypoint: ["/docker/entrypoint.sh"]
    volumes:
      - "./scripts:/docker"
      - "./vscode-server:/root/.vscode-server"
      - "./catkin_ws:/root/catkin_ws"
    devices:
      - "/dev:/dev"

    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    # runtime: nvidia
    runtime: nvidia


    network_mode: "host"