#! /bin/bash

# Setup of ROS Distributions
source /opt/ros/noetic/setup.bash
source /opt/ros/foxy/setup.bash

# Setup of ROS work spaces
source /root/catkin_ws/devel/setup.bash
source /root/ros2_ws/install/setup.bash
source /root/bridge_ws/install/setup.bash
export ROS_MASTER_URI=http://localhost:11311